# Generated by Django 4.2.5 on 2025-10-30 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('name', models.CharField(max_length=100, verbose_name='商品名')),
                ('price', models.IntegerField(default=0, verbose_name='価格')),
                ('image', models.ImageField(upload_to='images/', verbose_name='元の画像')),
                ('context', models.TextField(verbose_name='内容')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='商品コード')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='掲載日')),
            ],
            options={
                'db_table': 'product',
            },
        ),
    ]
