# Generated by Django 4.2.5 on 2025-11-12 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cart',
            field=models.IntegerField(default=0, verbose_name='カート数'),
        ),
    ]
