# Generated by Django 4.2.5 on 2025-11-20 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_product_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='cart',
        ),
    ]
