# Generated by Django 4.2.5 on 2026-03-11 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_cartitem_uniq_cart_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='session_id',
            field=models.CharField(max_length=40, null=True, unique=True),
        ),
    ]
