# Generated by Django 4.2.5 on 2025-10-27 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_details', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdetails',
            name='code',
            field=models.CharField(max_length=50, unique=True, verbose_name='商品コード'),
        ),
        migrations.AlterField(
            model_name='productdetails',
            name='context',
            field=models.TextField(verbose_name='内容'),
        ),
        migrations.AlterField(
            model_name='productdetails',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='掲載日'),
        ),
    ]
