# Generated by Django 4.2.5 on 2025-11-12 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Icon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='名前')),
                ('image', models.CharField(max_length=100, verbose_name='画像')),
            ],
            options={
                'db_table': 'icon',
            },
        ),
    ]
