# Generated by Django 4.2.5 on 2025-11-20 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='brief_description',
        ),
    ]
