# Generated by Django 4.2.5 on 2025-10-12 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_list', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='ProductList',
        ),
        migrations.AlterModelTable(
            name='productlist',
            table='product_list',
        ),
    ]
