# Generated by Django 4.2.5 on 2025-10-27 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_list', '0002_rename_product_productlist_alter_productlist_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productlist',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='productlist',
            name='image',
            field=models.ImageField(upload_to='images/', verbose_name='元の画像'),
        ),
        migrations.AlterField(
            model_name='productlist',
            name='name',
            field=models.CharField(max_length=100, verbose_name='商品名'),
        ),
        migrations.AlterField(
            model_name='productlist',
            name='price',
            field=models.IntegerField(default=0, verbose_name='価格'),
        ),
    ]
