# Generated by Django 4.2.5 on 2026-03-13 03:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Checkout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=30, verbose_name='姓')),
                ('first_name', models.CharField(max_length=30, verbose_name='名')),
                ('user_name', models.CharField(max_length=30, verbose_name='ユーザー名')),
                ('email', models.EmailField(max_length=254, verbose_name='メールアドレス')),
                ('zip_code', models.CharField(max_length=8, verbose_name='郵便番号')),
                ('prefecture', models.CharField(max_length=30, verbose_name='都道府県')),
                ('city', models.CharField(max_length=30, verbose_name='市区町村')),
                ('street_address', models.CharField(max_length=30, verbose_name='丁目・番地・号')),
                ('building_name', models.CharField(blank=True, max_length=30, verbose_name='建物名・部屋番号')),
                ('total_amount', models.IntegerField(default=0, verbose_name='合計金額')),
                ('total_quantity', models.IntegerField(default=0, verbose_name='合計数量')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='注文日時')),
            ],
            options={
                'db_table': 'checkout',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_holder', models.CharField(max_length=50, verbose_name='カード名義人')),
                ('card_number', models.CharField(max_length=19, verbose_name='カード番号')),
                ('expiration_date', models.CharField(max_length=10, verbose_name='有効期限')),
                ('cvv', models.CharField(max_length=3, verbose_name='セキュリティコード')),
                ('checkout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.checkout', verbose_name='請求情報')),
            ],
            options={
                'db_table': 'payment',
            },
        ),
        migrations.CreateModel(
            name='LineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='商品名')),
                ('price', models.IntegerField(default=0, verbose_name='価格')),
                ('quantity', models.IntegerField(default=1, verbose_name='数量')),
                ('subtotal_amount', models.IntegerField(default=0, verbose_name='小計')),
                ('checkout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.checkout', verbose_name='注文情報')),
            ],
            options={
                'db_table': 'line_item',
            },
        ),
    ]
