# Generated by Django 4.2.5 on 2025-11-19 03:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_alter_payment_cvv_alter_payment_expiration_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='LineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_item_name', models.CharField(max_length=100, verbose_name='商品名')),
                ('cart_item_price', models.IntegerField(default=0, verbose_name='価格')),
                ('cart_item_quantity', models.IntegerField(default=1, verbose_name='数量')),
                ('checkout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.checkout', verbose_name='注文情報')),
            ],
            options={
                'db_table': 'line_item',
            },
        ),
    ]
