# Generated by Django 4.2.5 on 2025-11-20 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_lineitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='checkout',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='checkout',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='注文日時'),
        ),
        migrations.AddField(
            model_name='checkout',
            name='total_amount',
            field=models.IntegerField(default=0, verbose_name='合計金額'),
        ),
        migrations.AddField(
            model_name='checkout',
            name='total_quantity',
            field=models.IntegerField(default=0, verbose_name='合計数量'),
        ),
        migrations.AddField(
            model_name='lineitem',
            name='cart_item_subtotal_amount',
            field=models.IntegerField(default=0, verbose_name='小計'),
        ),
    ]
