# Generated by Django 4.2.5 on 2026-03-11 13:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promo_code', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocode',
            name='code',
            field=models.CharField(blank=True, max_length=7, unique=True, validators=[django.core.validators.RegexValidator(message='プロモコードは英数字7桁で入力してください', regex='^[A-Za-z0-9]{7}$')], verbose_name='プロモコード'),
        ),
    ]
