# Generated by Django 4.2.5 on 2025-12-02 06:59

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0007_rename_cart_item_name_lineitem_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promo_code', models.CharField(blank=True, max_length=7, unique=True, validators=[django.core.validators.RegexValidator(message='プロモコードは英数字7桁で入力してください', regex='^[A-Za-z1-9]{7}$')], verbose_name='プロモコード')),
                ('discount', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(100), django.core.validators.MaxValueValidator(1000)], verbose_name='割引額')),
                ('is_used', models.BooleanField(default=False, verbose_name='使用済み')),
                ('used_checkout', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promo_code', to='order.checkout', verbose_name='適応された決済')),
            ],
            options={
                'db_table': 'promo_code',
            },
        ),
    ]
