# Generated by Django 4.2.5 on 2025-11-16 02:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Checkout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=30, verbose_name='姓')),
                ('first_name', models.CharField(max_length=30, verbose_name='名')),
                ('user_name', models.CharField(max_length=30, verbose_name='ユーザー名')),
                ('email', models.EmailField(max_length=254, verbose_name='メールアドレス')),
                ('zip_code', models.CharField(max_length=8, verbose_name='郵便番号')),
                ('prefecture', models.CharField(max_length=30, verbose_name='都道府県')),
                ('city', models.CharField(max_length=30, verbose_name='市区町村')),
                ('street_address', models.CharField(max_length=30, verbose_name='丁目・番地・号')),
                ('building_name', models.CharField(blank=True, max_length=30, verbose_name='建物名・部屋番号')),
            ],
            options={
                'db_table': 'checkout',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_holoder', models.CharField(max_length=50, verbose_name='カード名義人')),
                ('card_number', models.CharField(max_length=16, verbose_name='カード番号')),
                ('expiration_date', models.CharField(max_length=5, verbose_name='有効期限')),
                ('cvv', models.CharField(max_length=4, verbose_name='セキュリティコード')),
                ('checkout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.checkout', verbose_name='請求情報')),
            ],
            options={
                'db_table': 'payment',
            },
        ),
    ]
