# Generated by Django 4.2.5 on 2025-11-16 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='card_holoder',
            new_name='card_holder',
        ),
    ]
