# Generated by Django 4.2.5 on 2025-11-16 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_rename_card_holoder_payment_card_holder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='card_number',
            field=models.CharField(max_length=19, verbose_name='カード番号'),
        ),
    ]
