# Generated by Django 4.2.5 on 2025-11-16 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_alter_payment_card_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='cvv',
            field=models.CharField(max_length=3, verbose_name='セキュリティコード'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='expiration_date',
            field=models.CharField(max_length=10, verbose_name='有効期限'),
        ),
    ]
