# Generated by Django 4.2.5 on 2025-11-24 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_alter_checkout_options_checkout_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lineitem',
            old_name='cart_item_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='lineitem',
            old_name='cart_item_price',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='lineitem',
            old_name='cart_item_quantity',
            new_name='quantity',
        ),
        migrations.RenameField(
            model_name='lineitem',
            old_name='cart_item_subtotal_amount',
            new_name='subtotal_amount',
        ),
    ]
